### PR TITLE
use step functions to prevent "fat finger syndrome"

### PR DESCRIPTION
**Pull request by bacongobbler**

### CODE REVIEW

**Comment by bcardiff** [comment]
The fat syndrome you refer is for further development and creating log messages, right?

Since warn/err/step are not been used why they should be included?

**Comment by bacongobbler** [comment]
Yep, warn/err/step functions will be utilized in future PRs.

**Comment by bacongobbler** [comment]
I can pull them out if you'd prefer and add them in as they're introduced. Sounds good?

**Comment by bcardiff** [comment]
Yes, please. Pull them out & rebase.

**Comment by bacongobbler** [comment]
fixed

**Comment by bacongobbler** [comment]
Gah, thanks for catching that. More rebase issues

**Comment by bcardiff** [comment]
Understandable, you rewrote a lot :-).
Thanks for all the PRs and splitting them.

**Pull request merged**
